[vars]
SUPABASE_URL = "https://ecsyywbcltrtsskijuiz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjc3l5d2JjbHRydHNza2lqdWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEzMTI0NDgsImV4cCI6MjA0Njg4ODQ0OH0.IQBBeT7TzzwQ5i_nUxbLjbc5GKM_rCCv2Vpsx5lUAkY"